#!/usr/bin/env node
// Build per-platform turtleneck skill folders from the single source in src/.
//
//   node scripts/build.js          # write the generated platform folders
//   node scripts/build.js --check  # fail if any output is stale (for CI)
//
// Source of truth: src/body/ (router.md + modes/ + schema.md) and src/platforms.json.
// Generated output (skills/turtleneck, platforms/codex/turtleneck, ...) is committed
// and must never be hand-edited — edit src/ and rebuild.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");
const BODY = path.join(SRC, "body");
const cfg = JSON.parse(fs.readFileSync(path.join(SRC, "platforms.json"), "utf8"));

const check = process.argv.includes("--check");
// Placed AFTER the frontmatter (frontmatter must be the first bytes of the file,
// or skill parsers won't read it).
const GENERATED_NOTE =
  "<!-- GENERATED by scripts/build.js from src/ — do not edit. Edit src/body or src/platforms.json and run `npm run build`. -->\n\n";

// --- minimal YAML frontmatter emitter (handles strings, bools, arrays, one-level maps) ---
function yamlScalar(v) {
  if (typeof v === "boolean") return String(v);
  // Leave bare when it can't be misread as YAML structure: no leading indicator
  // char, and none of : flow/comment chars that force quoting. Allows e.g.
  // `Read Write Edit Bash(git:*) Grep` and `[init | review | pass]` to stay bare.
  const safeBare = /^[A-Za-z0-9 ._\/|()\[\]*+-]+$/.test(v) && !/^[-?:,\[\]{}#&*!|>'"%@`]/.test(v);
  if (safeBare) return v;
  return JSON.stringify(v); // double-quoted, escapes safely
}
function emitFrontmatter(name, description, fm) {
  const lines = ["---", `name: ${name}`, "description: >-"];
  // wrap description as a folded block so long text stays readable
  for (const chunk of wrap(description, 76)) lines.push("  " + chunk);
  for (const [k, v] of Object.entries(fm)) {
    if (Array.isArray(v)) {
      lines.push(`${k}:`);
      for (const item of v) lines.push(`  - ${yamlScalar(item)}`);
    } else if (v && typeof v === "object") {
      lines.push(`${k}:`);
      for (const [k2, v2] of Object.entries(v)) lines.push(`  ${k2}: ${yamlScalar(v2)}`);
    } else {
      lines.push(`${k}: ${yamlScalar(v)}`);
    }
  }
  lines.push("---", "");
  return lines.join("\n");
}
function wrap(text, width) {
  const words = text.split(/\s+/);
  const out = [];
  let line = "";
  for (const w of words) {
    if (line && (line + " " + w).length > width) {
      out.push(line);
      line = w;
    } else {
      line = line ? line + " " + w : w;
    }
  }
  if (line) out.push(line);
  return out;
}

function buildSkillMd(platform) {
  const router = fs.readFileSync(path.join(BODY, "router.md"), "utf8");
  const body = router.replaceAll("{{ARG}}", platform.arg);
  const fm = emitFrontmatter(cfg.shared.name, cfg.shared.description, platform.frontmatter);
  return fm + GENERATED_NOTE + body;
}

// Collect the full set of files each platform output should contain.
function plannedFiles(platform) {
  const files = new Map(); // relPath -> content
  files.set("SKILL.md", buildSkillMd(platform));
  files.set("schema.md", fs.readFileSync(path.join(BODY, "schema.md"), "utf8"));
  for (const f of fs.readdirSync(path.join(BODY, "modes"))) {
    files.set(path.join("modes", f), fs.readFileSync(path.join(BODY, "modes", f), "utf8"));
  }
  return files;
}

let stale = 0;
let wrote = 0;
for (const platform of cfg.platforms) {
  const outDir = path.join(ROOT, platform.out);
  const files = plannedFiles(platform);

  for (const [rel, content] of files) {
    const dest = path.join(outDir, rel);
    const current = fs.existsSync(dest) ? fs.readFileSync(dest, "utf8") : null;
    if (current === content) continue;
    if (check) {
      stale++;
      console.error(`stale: ${path.relative(ROOT, dest)}`);
    } else {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, content);
      wrote++;
    }
  }

  // In check mode, also flag stray files that the build would no longer produce.
  if (check && fs.existsSync(outDir)) {
    const expected = new Set([...files.keys()].map((r) => path.join(outDir, r)));
    const walk = (d) => {
      for (const e of fs.readdirSync(d, { withFileTypes: true })) {
        const p = path.join(d, e.name);
        if (e.isDirectory()) walk(p);
        else if (!expected.has(p)) {
          stale++;
          console.error(`stray: ${path.relative(ROOT, p)} (not produced by build)`);
        }
      }
    };
    walk(outDir);
  }
}

if (check) {
  if (stale) {
    console.error(`\n${stale} file(s) out of date. Run \`npm run build\` and commit.`);
    process.exit(1);
  }
  console.log("Build output is up to date.");
} else {
  console.log(`Build complete. ${wrote} file(s) written across ${cfg.platforms.length} platform(s).`);
}
